Gemeente-DenHaag/nl-portal-libraries

packages/localization/src/i18n/messages/en-gb.ts, packages/localization/src/i18n/messages/nl-nl.ts, packages/user-interface/src/pages/case/case-page.tsx, packages/user-interface/src/pages/cases/cases-page.tsx
Includes changes from https://github.com/Gemeente-DenHaag/nl-portal-libraries/pull/21. 
Closes https://ritense.tpondemand.com/entity/31571-portal-zaken-weergeven-foutafhandeling
=> feat: show message when error fetching data

.github/workflows/cicd.yml
=> feat: make adjustments to workflow file

.eslintignore, lerna.json, packages/app/src/components/app/app.tsx, packages/localization/src/i18n/messages/en-gb.ts, packages/localization/src/i18n/messages/nl-nl.ts, packages/user-interface/src/pages/account/account-page.module.scss, packages/user-interface/src/pages/account/account-page.test.tsx, packages/user-interface/src/pages/account/account-page.tsx, packages/user-interface/src/pages/account/index.ts, packages/user-interface/src/pages/index.ts
Closes https://ritense.tpondemand.com/entity/32563-contactgegevens-pagina
=> feat: add contact details page

packages/user-interface/src/components/index.ts, packages/user-interface/src/components/locale-date/index.ts, packages/user-interface/src/components/locale-date/locale-date.test.tsx, packages/user-interface/src/components/locale-date/locale-date.tsx, packages/user-interface/src/components/meta-icon/meta-icon.tsx, packages/user-interface/src/pages/case/case-page.tsx
Closes https://ritense.tpondemand.com/entity/32610-datumweergave-op-basis-van-locale-in
=> feat: format dates based on current locale

entrypoint.sh
=> fix: rest api in entrypoint file

packages/api/src/generated/graphql.tsx, packages/api/src/queries/get-document-content.ts, packages/api/src/queries/get-forms.ts, packages/app/public/config.js, packages/app/src/components/app/app.tsx, packages/app/src/styles/nl-portal-design-tokens.css, packages/localization/src/i18n/messages/en-gb.ts, packages/localization/src/i18n/messages/nl-nl.ts, packages/user-interface/src/components/index.ts, packages/user-interface/src/components/list-item-skeleton/index.ts, packages/user-interface/src/components/list-item-skeleton/list-item-skeleton.module.scss, packages/user-interface/src/components/list-item-skeleton/list-item-skeleton.test.tsx, packages/user-interface/src/components/list-item-skeleton/list-item-skeleton.tsx, packages/user-interface/src/pages/form/form-page.tsx, packages/user-interface/src/pages/forms/forms-page.module.scss, packages/user-interface/src/pages/forms/forms-page.test.tsx, packages/user-interface/src/pages/forms/forms-page.tsx, packages/user-interface/src/pages/forms/index.ts, packages/user-interface/src/pages/index.ts
Closes https://ritense.tpondemand.com/entity/33176-lijst-van-formulieren-tonen-in-portaal
=> feat: add page with list of forms

packages/user-interface/src/pages/form/form-page.tsx
Closes https://ritense.tpondemand.com/entity/33176-lijst-van-formulieren-tonen-in-portaal
=> fix: stay on correct form on authentication redirect

packages/user-interface/src/pages/form/form-page.tsx
Closes https://ritense.tpondemand.com/entity/33176-lijst-van-formulieren-tonen-in-portaal
=> fix: save form id in local storage

packages/app/src/components/app/app.tsx, packages/localization/src/i18n/messages/en-gb.ts, packages/localization/src/i18n/messages/nl-nl.ts, packages/user-interface/src/pages/form/form-page.tsx, packages/user-interface/src/pages/overview/overview-page.tsx
Closes https://ritense.tpondemand.com/entity/33176-lijst-van-formulieren-tonen-in-portaal
=> fix: fix persist of local storage persist form id

.github/workflows/cicd.yml, Dockerfile, packages/api/src/components/api-wrapper/api-wrapper.test.tsx
Add unittest stage in Dockerfile
Execute different stages in worflow
=> Execute unittests in workflow

packages/api/src/generated/graphql.tsx, packages/api/src/queries/get-persoon.ts, packages/user-interface/src/components/user-name/user-name.tsx, packages/user-interface/src/pages/forms/forms-page.tsx
Contributes to https://ritense.tpondemand.com/entity/30956-befe-portalheader-naam-vullen-met-haalcentraal
=> feat: get header user name from haalcentraal

packages/api/src/generated/graphql.tsx, packages/api/src/queries/get-persoon-data.ts, packages/user-interface/src/components/detail-list/detail-list.tsx, packages/user-interface/src/pages/account/account-page.tsx
Closes https://ritense.tpondemand.com/entity/32568-inzien-persoonsgegevens-op-accountpagina
=> feat: show personal data from haalcentraal on account page

packages/api/src/generated/graphql.tsx, packages/api/src/queries/get-persoon-data.ts, packages/app/src/styles/nl-portal-design-tokens.css, packages/user-interface/src/components/user-name/user-name.module.scss, packages/user-interface/src/components/user-name/user-name.tsx, packages/user-interface/src/pages/account/account-page.tsx, packages/user-interface/src/pages/forms/forms-page.tsx
Fixes circular imports forms page, overflow of username in header and adds extra fields to address. Closes https://ritense.tpondemand.com/entity/32568-inzien-persoonsgegevens-op-accountpagina
=> feat: finalize person data functionality

packages/user-interface/src/pages/account/account-page.tsx
=> fix: correct date of birth on account page

packages/api/src/generated/graphql.tsx, packages/api/src/queries/get-persoon-data.ts, packages/api/src/queries/get-persoon.ts, packages/user-interface/src/components/user-name/user-name.tsx, packages/user-interface/src/pages/account/account-page.tsx, packages/user-interface/src/utils/index.ts, packages/user-interface/src/utils/person-data.test.tsx, packages/user-interface/src/utils/person-data.tsx
includes refactor: moved functions having to do with person data to separate utils file, added unit tests for these functions. Adds support of voorvoegsel prop in name object. Closes https://ritense.tpondemand.com/entity/33727-volledige-naam-weergeven
=> feat: add prefix to person name

packages/app/src/components/app/app.tsx, packages/user-interface/src/pages/form/form-page.tsx
To allow refreshing during from within the form and make sure automatic sign in can redirect to the form
=> fix: add child path for forms

package.json, packages/api/src/generated/graphql.tsx, packages/api/src/queries/get-form.ts, packages/api/src/queries/get-taken.ts, packages/app/src/components/app/app.tsx, packages/localization/src/i18n/messages/en-gb.ts, packages/localization/src/i18n/messages/nl-nl.ts, packages/user-interface/package.json, packages/user-interface/src/pages/index.ts, packages/user-interface/src/pages/task/index.ts, packages/user-interface/src/pages/task/task-page.test.tsx, packages/user-interface/src/pages/task/task-page.tsx, packages/user-interface/src/pages/tasks/tasks-page.tsx, yarn.lock
Added first version of task page copied from amsterdam
=> Added task page

packages/user-interface/package.json
```
#10 18.01 Cannot find module: 'formiojs'. Make sure this package is installed.
```
=> Add 'formiojs'

package.json, packages/api/package.json, packages/app/package.json, packages/authentication/package.json, packages/localization/package.json, packages/user-interface/package.json, yarn.lock
=> feat: improve cli

SECURITY.md, packages/user-interface/src/pages/account/account-page.tsx, packages/user-interface/src/pages/overview/overview-page.tsx
Added some configuration options to make it possible to show/hide content
=> feat: added some extra configuration options to show/hide content

packages/user-interface/src/components/file-upload/file-upload.tsx, packages/user-interface/src/components/form-io-uploader/form-io-uploader.tsx
Closes https://ritense.tpondemand.com/entity/54635-nl-portal-fe-document-metadata
=> feat: add document metadata to file uploads

packages/api/src/components/api-wrapper/api-wrapper.tsx, packages/api/src/constants/index.ts, packages/api/src/constants/token.ts, packages/api/src/index.ts, packages/api/src/interfaces/index.ts, packages/api/src/interfaces/token.ts, packages/user-interface/src/components/file-upload/file-upload.tsx
=> feat: read token from object in formio upload component
